### ISSUE TITLE
# as start / part of name

### ISSUE THREAD

**Issue by azuendorf** [Kuenssi/fulibWorkflows-editor#45]
e.g. #900

**Comment by Kuenssi** [comment]
`#` markieren einen Kommentar in YAML.
Nicht nur, dass damit der neue Parser nicht umgehen kann, auch Editoren zeigen bereits an, dass das was ganz anderes zu sein scheint.

Als Bezeichner für ein Objekt ist das nicht nutzbar.
Innerhalb eines Strings der mit Hochkommata markiert sind, können `#` verwendet werden.
Folgendes Beispiel würde funktionieren.
```yaml
- data: Student carli
  motivation: "#900"
```
